const JOURNEY = {
  title: "The Road That Gave Me a Sister",
  startCenter: [18.5699601010909, 73.91580890479796],
  startZoom: 12,
  homeId: "smart-living-pg",
  carMemory: {
    title: "Memories From the Road",
    place: "Inside the car",
    story: "Some of the best parts of Pune happened between destinations.",
    quote: "Some memories belong to places. These belonged to the road.",
    photos: [],
    videos: [],
    voice: [],
  },
  dialogue: [
    "Are we there yet?",
    "You picked the route.",
    "Still blaming you.",
    "Some roads are worth taking twice.",
    "Good thing we took pictures.",
  ],
  memories: [
    {
      id: "aeromall",
      order: 1,
      title: "Where the Pune chapter begins",
      place: "AeroMall, Pune Airport",
      coords: [18.577774, 73.90724],
      icon: "✈️",
      story: "Add your story here.",
      quote: "Every unforgettable chapter starts with an ordinary arrival.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "apollo",
      order: 2,
      title: "The dramatically unnecessary hospital stop",
      place: "Apollo, Viman Nagar",
      coords: [18.564603010455283, 73.91391886100888],
      icon: "🏥",
      story: "Add your story here.",
      quote: "Next time we miss each other, a café will do.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "decathlon",
      order: 3,
      title: "A very serious sporting expedition",
      place: "Decathlon",
      coords: [18.576903755649422, 73.97038542616801],
      icon: "⚽",
      story: "Add your story here.",
      quote: "Some errands become memories only because of who comes along.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "phoenix",
      order: 4,
      title: "Where time and money both disappeared",
      place: "Phoenix Marketcity, Viman Nagar",
      coords: [18.5621, 73.9167],
      icon: "🛍️",
      story: "Add your story here.",
      quote:
        "The place was crowded. Somehow, the memory still feels like ours.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "Sash",
      order: 5,
      title: "Good food, better company",
      place: "Sash Cocktail Bar & Kitchen",
      coords: [18.565479282648212, 73.91369728198859],
      icon: "🍹",
      story: "Add your story here.",
      quote:
        "A table, too much laughter, and another ordinary day made special.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "spice-factory",
      order: 6,
      title: "The spicy chapter",
      place: "Spice Factory",
      coords: [18.536785348977347, 73.9101530261518],
      icon: "🌶️",
      story: "Add your story here.",
      quote: "The food may be forgotten. The nonsense definitely will not be.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "iskcon",
      order: 7,
      title: "A quieter memory",
      place: "ISKCON Pune",
      coords: [18.524101896101627, 73.87996371774636],
      icon: "🪷",
      story: "Add your story here.",
      quote:
        "Some memories are loud. The meaningful ones do not always need to be.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "chaturshringi",
      order: 8,
      title: "A little peace above the city",
      place: "Chaturshringi Temple",
      coords: [18.5389889, 73.8282222],
      icon: "🙏",
      story: "Add your story here.",
      quote: "The city looked different from here. Maybe life did too.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "khadakwasla",
      order: 9,
      title: "The road away from the noise",
      place: "Khadakwasla Dam",
      coords: [18.43737408793662, 73.77173024147595],
      icon: "🌊",
      story: "Add your story here.",
      quote: "Some of the best memories begin by leaving the city behind.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "ganesh-mandir",
      order: 10,
      title: "The familiar corner",
      place: "Ganesh Mandir near Smart Living PG",
      coords: [18.568010503669644, 73.91837746841104],
      icon: "🛕",
      story: "Add your story here.",
      quote:
        "Not every landmark is famous. Some matter because they were ours.",
      photos: [],
      videos: [],
      voice: [],
    },
    {
      id: "smart-living-pg",
      order: 11,
      title: "Home",
      place: "Smart Living PG, Viman Nagar",
      coords: [18.570020709000566, 73.91569973781489],
      icon: "🏠",
      isHome: true,
      story:
        "Pune was full of places. But this was where the city began feeling like home.",
      quote:
        "When I came to Pune, I expected experience. I did not expect to leave with a sister.",
      photos: [],
      videos: [],
      voice: [],
    },
  ],
  landmarks: [
    { name: "Shaniwar Wada", coords: [18.5195, 73.8553], icon: "🏰" },
    { name: "Aga Khan Palace", coords: [18.5524, 73.9015], icon: "🏛️" },
    { name: "Dagdusheth Ganpati", coords: [18.5164, 73.8561], icon: "🛕" },
    { name: "Pune Railway Station", coords: [18.5289, 73.8744], icon: "🚉" },
    { name: "Saras Baug", coords: [18.5011, 73.852], icon: "🌳" },
    { name: "Pataleshwar Caves", coords: [18.5268, 73.8494], icon: "🪨" },
    { name: "Pune University", coords: [18.5525, 73.8246], icon: "🎓" },
    { name: "Parvati Hill", coords: [18.4973, 73.8443], icon: "⛰️" },
    { name: "Koregaon Park", coords: [18.5362, 73.8939], icon: "🌿" },
    { name: "FC Road", coords: [18.5222, 73.8417], icon: "☕" },
    { name: "Bund Garden", coords: [18.5385, 73.8846], icon: "🌳" },
    { name: "Sinhagad Fort", coords: [18.3663, 73.7559], icon: "🏰" },
  ],
};
